apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: default
---
# ADMIN_SECRET=$(kubectl get secret $(kubectl get serviceaccount admin-user -o jsonpath='{.secrets[0].name}') -o go-template='{{.data.token | base64decode}}')
# kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}'
# curl --insecure --header "Authorization: Bearer $ADMIN_SECRET" API_SERVER_URL/api/v1/nodes
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
